### ISSUE TITLE
Error checking logic missing - "Trying to access array offset on value of type bool"

### ISSUE THREAD

**Issue by higuhi** [RadarsofthouseDev/reepay-payment-for-magento2#14]
Many of the helper functions in Radarsofthouse\Reepay\Helper return "false" when Reepay REST API responds with an error. 

But, some caller functions seem to expect an array of data instead of a boolean value, so we get  "Trying to access array offset on value of type bool" when Reepay responds with an error. 

I think it should be more robust by changing the caller functions to check the return value. 

I picked this one, but there could be other places that need to be fixed as well. 

https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/blob/master/Helper/Payment.php#L200

**Comment by RadarsofthouseDev** [comment]
@higuhi We just released new version (1.2.26) which included the fix :)
https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/releases/tag/1.2.26
