### ISSUE TITLE
[Bug] missing __( ) function around the argument when throwing a LocalizedException 

### ISSUE THREAD

**Issue by HeydayApS** [RadarsofthouseDev/reepay-payment-for-magento2#3]
### Issue description
The arguments for LocalizedExceptions in the following observers are incorrect, resulting in termination and preventing caller to handle the LocalizedExceptions using try-catch. 
- [Observer/SalesOrderPaymentCapture.php](https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/blob/9f219347ec64de67ec71fabb7f58e0b2f235e2f2/Observer/SalesOrderPaymentCapture.php)
- [Observer/SalesOrderPaymentRefund.php](https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/blob/9f219347ec64de67ec71fabb7f58e0b2f235e2f2/Observer/SalesOrderPaymentRefund.php)

For example, the following code in Observer/SalesOrderPaymentCapture.php (Line78) will result in termination, because LocalizedException's constructor expects a Phrase insted of **a string**.  The string argument should be enclosed by the  __() special function. 

> **Incorrect**
> `throw new \Magento\Framework\Exception\LocalizedException($charge["error"]);`
> 
> **Correct**
> `throw new \Magento\Framework\Exception\LocalizedException(__($charge["error"]));`

This is critical because we cannot catch "Capture Failure" and handle it properly when Reepay responses with error at payment capture. 

### Affected code 
I think the following lines of code need  __(  )  function.  

- https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/blob/9f219347ec64de67ec71fabb7f58e0b2f235e2f2/Observer/SalesOrderPaymentCapture.php#L78
- https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/blob/9f219347ec64de67ec71fabb7f58e0b2f235e2f2/Observer/SalesOrderPaymentCapture.php#L113
- https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/blob/9f219347ec64de67ec71fabb7f58e0b2f235e2f2/Observer/SalesOrderPaymentRefund.php#L76

### Steps to reproduce the issue
1. As a Magento admin, enable _Reepay payment_ under STORES > Configuration > SALES > Payment Methods, setting "Auto Capture" to "No"
2. As a customer, purchase something and place an order with credit card using repay (This will authorize the payment)
3. As a Reepay admin, open Reepay dashboard and cancel the authorized payment from the invoice menu
4. As a Magento admin, invoice the order with Auto Capture 
5. Invoicing fails because it is no longer authorized, but the `LocalizedException` from _SalesOrderPaymentCapture.php_ will not be delivered properly because incorrect argument for `LocalizedException` triggers another exception and results in termination without going through normal try-catch handling by the caller.

**Comment by RadarsofthouseDev** [comment]
Hi HeydayApS,

We have fixed the issue on version 1.2.4
Thanks for your issue report :)

**Comment by HeydayApS** [comment]
Great!  The update works perfectly 👍 
Tak for det!
