### ISSUE TITLE
Invoice generation when order is cancelled

### ISSUE THREAD

**Issue by sm131313** [RadarsofthouseDev/reepay-payment-for-magento2#5]
Case senario:
If someone places an order, status goes to pending. Goes to payment page and then switches tabs, considers, thinks, sleep and will complete payment tomorrow. Open up the computer next day and think ahh lets complete the payment now. 
What happens in between here is that almost every store has an automatic cancel pending orders not paid within XX hours to free up stock. So status in Magento goes to canceled and stock is free'd.  
When user now completes payment while Magento status is cancelled it will change the status of Magento order to Closed instead and payment will not be registered in Magento. 
A mad customer contacts store few days after and wonders why the order has not been shipped yet. 

So:
Reepay Payment window is active for 150+ days. 
Magento automatically cancels orders if payment is not registered within XX hours/days to free up stock again.
User completes payment after Magento freed up stock (status canceled)
Extension behaviour makes Magento change order status from cancelled to closed instead with no payment registered. 

Solution:
If payment arrives after order is cancelled, extension should uncancel the order and invoice it (goes to processing) again. Not go to Closed without any invoice generated.

**Comment by RadarsofthouseDev** [comment]
@sm131313 We have updated the module.
Version 1.2.10 on 7 October 2021
[https://github.com/RadarsofthouseDev/reepay-payment-for-magento2/releases/tag/1.2.10](url)
- Delete the charge when order is canceled from Magento (only not paid order). So, user cannot pay after cancel order.
